trigger:
- '*'

pool:
  name: 'Default' #test

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 8.x'
  inputs:
    packageType: sdk
    version: '8.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    command: 'install'
    verbose: false

#  Sass compilation with Bash shell and directory check
- powershell: |
    $scssPath = "Tailspin.SpaceGame.Web/wwwroot/scss"
    if (Test-Path $scssPath) {
      Write-Host " SCSS directory found. Compiling..."
      npx sass Tailspin.SpaceGame.Web/wwwroot/scss:Tailspin.SpaceGame.Web/wwwroot/css
    } else {
      Write-Host " SCSS directory not found. Skipping Sass compilation."
    }
  displayName: 'Compile Sass assets'


- script: 'npx gulp'
  displayName: 'Run gulp tasks'
  workingDirectory: Tailspin.SpaceGame.Web


- script: |
    echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot
- script: 'npx gulp'
  displayName: 'Run gulp tasks'
  workingDirectory: Tailspin.SpaceGame.Web

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Publish the project - Release'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()